use_frameworks!
platform :ios, '8.0'

target 'TextureSimply_Example' do
  pod 'TextureSimply', :path => '../'
  pod 'MJRefresh'
  pod 'Moya'

  target 'TextureSimply_Tests' do
    inherit! :search_paths

    
  end
end
